# Re-arrange things to better match my preferences.
# See <https://starship.rs/config> for details.
format = """
$time\
$cmd_duration\
$line_break\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""


[aws]

# Disable this module, as it's mostly noise for my use cases.
disabled = true


[cmd_duration]

# Always display command duration.
min_time = 0
show_milliseconds = true

# Enable desktop notifications for longer commands.
show_notifications = true
min_time_to_notify = 45_000


[git_metrics]

# Enable this module (it's disabled by default).
disabled = false


[ruby]
# Given RVM is always active, we don't need this module triggering in every directory.
# The `detect_{extensions,files}` variables should ensure it's triggered in actual Ruby projects.
detect_variables = []


[time]

# Enable this module (it's disabled by default).
disabled = false

# Include the date & TZ.
format = "[$time]($style), "
time_format = "%Y-%m-%dT%H:%M:%S%:z"
