##
# Starship Prompt Configuration
#
# Largely based on this preset: <https://starship.rs/presets/tokyo-night>.
##
format = """
[░▒▓](#a3aed2)\
[ $os ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#394260 bg:#212736)\
$time\
[](fg:#212736 bg:#1d2230)\
$cmd_duration\
[ ](fg:#1d2230)\
\n$character"""


# Git seems to run a bit too slow on my work laptop for the default (500 milliseconds).
command_timeout = 2000


[os]
disabled = false
format = "$symbol"
style = "bold"

[os.symbols]
Macos = ""

[directory]
format = "[ $path ]($style)"
style = "fg:#e3e5e5 bg:#769ff0"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'
style = "bg:#394260"

[git_status]
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
style = "bg:#394260"

[git_metrics]
# Enable this module (it's disabled by default).
disabled = false
format = '([+$added]($added_style) )[bg:#394260]([-$deleted]($deleted_style) )[bg:#394260]'
added_style = "fg:green bg:#394260"
deleted_style = "fg:red bg:#394260"

[time]
# Enable this module (it's disabled by default).
disabled = false
time_format = "%R"
format = '[[  $time ](fg:#a0a9cb bg:#212736)]($style)'
style = "bg:#212736"

[cmd_duration]
# Always display command duration.
min_time = 0
format = "[\ueba2 $duration]($style)"
style = "bg:#1d2230"
show_milliseconds = true
# Enable desktop notifications for longer commands.
#
# Note: On sway, this requires `mako`, with the following fix:
# <https://github.com/emersion/mako/issues/257#issuecomment-1049087860>.
show_notifications = true
min_time_to_notify = 45_000
