##
# Starship Prompt Configuration
#
# Largely based on this preset: <https://starship.rs/presets/tokyo-night>.
##
format = """
[░▒▓](#a3aed2)\
[ $os ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#394260 bg:#212736)\
$time\
[](fg:#212736 bg:#1d2230)\
$cmd_duration\
[ ](fg:#1d2230)\
\n$character"""


# Git seems to run a bit too slow on my work laptop for the default (500 milliseconds).
command_timeout = 2000


[os]
format = "$symbol"
style = "bold"
disabled = false

[os.symbols]
Macos = ""


[git_metrics]
# Enable this module (it's disabled by default).
disabled = false


[time]
# Enable this module (it's disabled by default).
disabled = false
# Include the date & TZ.
format = "$time"
time_format = " %R"


[cmd_duration]
# Always display command duration.
min_time = 0
format = "\ueba2 $duration"
show_milliseconds = true
# Enable desktop notifications for longer commands.
#
# Note: On sway, this requires `mako`, with the following fix:
# <https://github.com/emersion/mako/issues/257#issuecomment-1049087860>.
show_notifications = true
min_time_to_notify = 45_000
